import localFont from "next/font/local";
import {Noto_Sans, Rubik_Glitch , Rock_Salt} from '@next/font/google';
import "./globals.css";

const rockSalt = Rock_Salt({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-Rock_Salt'
});

const RubikGlitch = Rubik_Glitch({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-Rubik_Glitch'
})

const NotoSans = Noto_Sans({
  subsets:["latin"],
  weight: '400',
  display: 'swap',
  variable: '--font-Noto_Sans'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${rockSalt.variable} ${RubikGlitch.variable} ${NotoSans.variable}`}>
        {children}
      </body>  
    </html>
  );
}



